plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ikramkheshgi.popupdetector'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ikramkheshgi.popupdetector'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            // Temporary: use Android's default debug signing
            // for testing only.
            signingConfig signingConfigs.debug
        }
    }
}
